variables:
  GIT_SUBMODULE_STRATEGY: recursive
  VIVADO_PATH: "/opt/Xilinx/Vivado/2018.1/bin/vivado"
  PROJECT_DIR: "vivado"
  PROJECT_NAME: "TrivialMIPS"
  TOP_MODULE_NAME: "ThinPad"


# all files in ip dir except *.xci are ignored, so the generated result will be cleaned every build
# to avoid generating from scratch every time, the dir should be cached
cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - ${PROJECT_DIR}/${PROJECT_NAME}.srcs/ip
    - ${PROJECT_DIR}/${PROJECT_NAME}.runs
    - ${PROJECT_DIR}/${PROJECT_NAME}.cache

stages:
  - build_ip
  - build_project
  - build_testbench
  - run_testbench

before_script:
  - cd ${PROJECT_DIR}
  # the cached ip configuration file might be out of date, we should always use the newest one
  - git checkout ${PROJECT_NAME}.srcs/ip

ip:
  image: vivado:2018.1
  tags:
    - vivado
  stage: build_ip
  script:
    - ${VIVADO_PATH} -mode tcl -source scripts/generate_all_ip.tcl ${PROJECT_NAME}.xpr


bitstream:
  image: vivado:2018.1
  tags:
    - vivado
  stage: build_project
  script:
    - ${VIVADO_PATH} -mode tcl -source scripts/build_project.tcl ${PROJECT_NAME}.xpr
  artifacts:
    paths:
      - ${PROJECT_DIR}/${PROJECT_NAME}.runs/impl_1/${TOP_MODULE_NAME}.bit
      - ${PROJECT_DIR}/${PROJECT_NAME}.runs/*/runme.log
    when: always


.mips_compilation_configuration: &mips_compilation_configuration
  image: harryleafchen/ubuntu-mips-compiler
  tags:
    - mips
  stage: build_testbench
  script:
    - make

compile_func_test:
  <<: *mips_compilation_configuration
  before_script:
    - cd software/func_test
  artifacts:
    paths:
      - software/func_test/main.elf

compile_perf_test:
  <<: *mips_compilation_configuration
  before_script:
    - cd software/perf_test
  artifacts:
    paths:
      - software/perf_test/obj/*/main.elf


test_on_cloud:
  image: python:3.7.0-stretch
  tags:
    - mips
  stage: run_testbench
  before_script:
    - cd testbench/cloud
    - pip3 install --user -r thinpad_cloud_sdk/requirements.txt
  script:
    - python3 cloud_test.py "$THINPAD_CLOUD_USER" "$THINPAD_CLOUD_PASSWD" ../../${PROJECT_DIR}/${PROJECT_NAME}.runs/impl_1/${TOP_MODULE_NAME}.bit
