stages:
  - build

bitstream:
  stage: build
  script:
    - env
    - docker run -t --rm -v $PWD:/home/vivado/project vivado:2018.1 /opt/Xilinx/Vivado/2018.1/bin/vivado -mode tcl -source vivado/build.tcl vivado/TrivialMIPS.xpr

  artifacts:
    paths:
      - vivado/TrivialMIPS.runs/impl_1/ThinPad.bit
