stages:
  - build

bitstream:
  tags:
    - vivado
  stage: build
  script:
    - env
    - /opt/Xilinx/Vivado/2018.1/bin/vivado -mode tcl -source vivado/build.tcl vivado/TrivialMIPS.xpr

  artifacts:
    paths:
      - vivado/TrivialMIPS.runs/impl_1/ThinPad.bit
      - vivado/TrivialMIPS.runs/synth_1/runme.log
      - vivado/TrivialMIPS.runs/impl_1/runme.log
